project:
  machine_name: specbee123
  prefix: SB
  human_name: "Specbee"
  repo: git@bitbucket.org:specbee/project-repo.git
  mail: no-reply@specbee.com
remotes:
  dev:
    host: ""
    user: ""
    root: ""
    uri: ""
  stage:
    host: ""
    user: ""
    root: ""
    uri: ""
sync:
  remote: "dev"
  sanitize: true
