name: #PROJECT_NAME
recipe: drupal9
config:
  webroot: docroot
  php: 7.4
  xdebug: false
  drush: '*'
services:
  appserver:
    environment:
      DRUSH_OPTIONS_ROOT: /app/docroot
      DRUSH_OPTIONS_URI: #PROJECT_NAME.lndo.site
      MINK_DRIVER_ARGS: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
      MINK_DRIVER_CLASS: 'Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver'
      SIMPLETEST_DB: "mysql://drupal:drupal@database/drupal"
      SIMPLETEST_BASE_URL: "https://#PROJECT_NAME.lndo.site"
      SYMFONY_DEPRECATIONS_HELPER: 'disabled'
      PHP_IDE_CONFIG: "serverName=appserver"
      BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://#PROJECT_NAME.lndo.site"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/docroot" }}}}'
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  node:
    type: node:14
    globals:
      gulp-cli: latest
      npm: latest
      yarn: latest
  database:
    type: mariadb:10.4
    creds:
      user: drupal
      password: drupal
      database: drupal
tooling:
  chromedriver:
    service: chromedriver
    description: "Run chromedriver commands."
  behat:
    service: appserver
    description: Run behat tests locally.
    cmd:
      - /app/vendor/bin/behat
  yarn:
    service: node
  setup:
    service: appserver
    description: Install Drupal.
    cmd:
      - echo '\033[0;33m>> Setting up local environment... \033[0m'
      - composer install -vvv
      - composer setup-local -vvv
      - robo drupal:install
      - drush uli
  drupal:update:
    service: appserver
    description: Update Drupal database & configurations
    cmd:
      - echo '\033[0;33m>> Updating Drupal database & configurations... \033[0m'
      - composer install -vvv
      - robo drupal:update
  sync:all:
    service: appserver
    description: Sync database and files from remote origin
    cmd:
      - echo '\033[0;33m>> Syncing database & files assets from remote server... \033[0m'
      - robo sync:db
      - robo import:config
      - robo sync:files
      - drush uli
  sync:db:
    service: appserver
    description: Sync database from remote origin
    cmd:
      - echo '\033[0;33m>> Syncing database assets from remote server... \033[0m'
      - robo sync:db
      - robo import:config
      - drush uli
  sync:files:
    service: appserver
    description: Sync files from remote origin
    cmd:
      - echo '\033[0;33m>> Syncing files assets from remote server... \033[0m'
      - robo sync:files
  validate:all:
    service: appserver
    description: Validating standards on code.
    cmd:
      - echo '\033[0;33m>> Validating standards on code.... \033[0m'
      - robo validate:composer
      - robo validate:phpcs:sniff
      - robo validate:frontend:src
  init:service:search:
    service: appserver
    description: Add Elasticsearch support to the app
    cmd:
      - robo init:service:search
  init:service:cache:
    service: appserver
    description: Add Redis cache support to the app
    cmd:
      - robo init:service:cache
  test:run:all:
    service: appserver
    description: Run behat tests & PHPUnit test locally.
    cmd:
      - robo test:run:phpunit
      - robo test:run:behat
  test:run:behat:
    service: appserver
    description: Run behat tests locally.
    cmd:
      - robo test:run:behat
  test:run:phpunit:
    service: appserver
    description: Run PHPUnit test locally.
    cmd:
      - robo test:run:phpunit
