#!/usr/bin/env bash

# Serve the Drupal application for the /app directory.

set -e

if [[ "${BITBUCKET_CLONE_DIR}" ]]; then
  chown -R www-data:www-data $BITBUCKET_CLONE_DIR
  ln -sf $BITBUCKET_CLONE_DIR/* /app
  service apache2 restart
  cd /app
fi
